[package]
name = "token-voter"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "token_voter"

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "proposal/idl-build"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
devnet = []
serde-feature = ["serde"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
proposal = { path = "../proposal", features = ["no-entrypoint", "cpi"] }
serde = { version = "1.0", features = ["derive"], optional = true }