[package]
name = "organization"
version = "0.1.1"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "organization"

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "proposal/idl-build"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
devnet = []

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
proposal = { path = "../proposal", features = ["no-entrypoint", "cpi"] }

[lints]
workspace = true
